# All SpaceVim option below [option] section
[options]
    colorscheme = "new-moon"
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[custom_plugins]]
  name = "dylanaraps/wal.vim"
  name = "taniarascia/new-moon.vim"
