[options]
enable_guicolors = true
colorscheme = 'base16-tomorrow-night-eighties'

[[layers]]
name = 'autocomplete'

[[layers]]
name = 'format'

[[layers]]
name = 'git'

[[layers]]
name = 'lang#typescript'

[[custom_plugins]]
name = 'chriskempson/base16-vim'
