" vimrc by Jonathan Dahan <jonathan@jedahan.com>
" to install:
" mkdir -p ~/.vim/bundle
" git clone http://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
" ln -s ~/.vim/vimrc ~/.vimrc

" vundle is a package manager for vim scripts
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'Command-T'
let g:CommandTMatchWindowAtTop=1 " show window at top
Bundle 'mattn/gist-vim'
let g:gist_clip_command = 'pbcopy'
let g:gist_detect_filetype = 1
Bundle 'SuperTab'
Bundle 'jQuery'
Bundle 'JSON.vim'
Bundle 'groenewege/vim-less'
Bundle 'surround.vim'
Bundle 'joseluisdgz/TaskVim'
Bundle 'ctags.vim'
Bundle 'vim-coffee-script'
Bundle 'altercation/vim-colors-solarized'
Bundle 'digitaltoad/vim-jade'
Bundle 'plasticboy/vim-markdown'
Bundle 'tclem/vim-arduino'
Bundle 'scrooloose/syntastic'
Bundle 'Tagbar'

" use git for backups
set noswapfile
set nobackup

" number lines
set nocompatible
set number

" colors
filetype plugin indent on
syntax on
set background=dark
colorscheme solarized

" soft and hard tabs at 2 spaces
set vb t_vb=
set ts=2 sts=2 sw=2 expandtab

" search immediately, ignoring case most of the time
set hlsearch
set incsearch
set ignorecase
set smartcase

" ignore dumb files
set wildignore=*.swp,*.bak,*.pyc,*.class

" tweaks
set title
set visualbell
set noerrorbells
set mouse=a

" show trailing whitespace
set list
set listchars=tab:>.,trail:.,extends:#,nbsp:.

" faster searching
map <space> /
map <c-space> ?

autocmd BufNewFile,BufRead *.json set ft=json

" coffeetags --vim-conf --include-vars
 let g:tagbar_type_coffee = {
  \ 'kinds' : [
  \   'f:functions',
  \   'o:object'
  \ ],
  \ 'kind2scope' : {
  \  'f' : 'object',
  \   'o' : 'object'
  \},
  \ 'sro' : ".",
  \ 'ctagsbin' : 'coffeetags',
  \ 'ctagsargs' : '--include-vars ',
  \}
