" vimrc by Jonathan Dahan <jonathan@jedahan.com>
" to install:
" mkdir -p ~/.vim/bundle
" git clone http://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
" ln -s ~/.vim/vimrc ~/.vimrc

set scrolloff=8         "Start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1


set autoread
set nocompatible
syntax enable
set encoding=utf-8
set showcmd                     " display incomplete commands
filetype plugin indent on       " load file type plugins + indentation

"" Whitespace
set nowrap                      " don't wrap lines
set tabstop=2 shiftwidth=2      " a tab is two spaces (change this to your linking)
set expandtab                   " use spaces, not tabs (remove this if you mostly use tabs)
set backspace=indent,eol,start  " backspace through everything in insert mode

"" Searching
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

" vundle is a package manager for vim scripts
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'vundle'
Bundle 'Command-T'
let g:CommandTMatchWindowAtTop=1 " show window at top
Bundle 'ctags.vim'
let g:tagbar_ctags_bin = '/usr/local/bin/ctags'
Bundle 'altercation/vim-colors-solarized'

Bundle 'jQuery'
Bundle 'JSON.vim'
Bundle 'vim-coffee-script'
Bundle 'tclem/vim-arduino'
Bundle 'plasticboy/vim-markdown'
Bundle 'ctrlp.vim'
Bundle 'sickill/vim-pasta'

" use git for backups
set noswapfile
set nobackup

" number lines
set number

" colors
set background=dark

" ignore dumb files
set wildignore=*.swp,*.bak,*.pyc,*.class

" tweaks
set title
set visualbell
set noerrorbells
set mouse=a

" show trailing whitespace
set list
set listchars=tab:>.,trail:.,extends:#,nbsp:.

" faster searching
map <space> /
map <c-space> ?

autocmd BufNewFile,BufRead *.json set ft=json

" coffeetags --vim-conf --include-vars
 let g:tagbar_type_coffee = {
  \ 'kinds' : [
  \   'f:functions',
  \   'o:object'
  \ ],
  \ 'kind2scope' : {
  \  'f' : 'object',
  \   'o' : 'object'
  \},
  \ 'sro' : ".",
  \ 'ctagsbin' : 'coffeetags',
  \ 'ctagsargs' : '--include-vars ',
  \}

set guifont=Inconsolata:h24
