theme = "slick"
icons = "awesome"

[[block]]
block = "net"
device = "wlan0"
ssid = true
ip = true
interval = 60
speed_up = false
speed_down = false
hide_inactive = true
hide_missing = true

[[block]]
block = "net"
device = "enx3c18a0d251a9"
ip = true
interval = 60
speed_up = false
speed_down = false
hide_inactive = true
hide_missing = true

[[block]]
block = "battery"
interval = 60
format = "{time}"

[[block]]
block = "sound"
format = ""

[[block]]
block = "time"
interval = 60
format = "%R"
