theme = "base16_transparent"

[editor]
bufferline = "always"

[keys.normal.space.b]
f = ":format"
s = ":write"
c = ":buffer-close"
n = ":buffer-next"
p = ":buffer-previous"

[editor.file-picker]
hidden = false

